# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa31791f8eeb88dd693df15400c4d3f5a721979758799eddd2e8167b385d5d195473a5509e65ed2a512bfb0739b5b031b2b89d3a55a3dd422ea693bba131eec9

test:
  secret_key_base: b431010b7bafdf603ca1335e265d17c1010de975df2a908736665ffa477af63741b6b2cc30fe181adb1ff36845d768815de8ada2d8c99049ca9eb72bd506f262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
